name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Compatible avec Dart 3+

dependencies:
  flutter:
    sdk: flutter
  
  # La dépendance pour glisser (swiper)
  flutter_slidable: ^3.1.1 
  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true